### ISSUE TITLE
Don't remove Provision app when skipping SetupWizard install on LOWMEM or LOW_STORAGE devices

### ISSUE THREAD

**Issue by pdsouza** [MindTheGapps/vendor_gapps-old#12]
I found an issue when using MindTheGapps on my Nexus 5 (running [Maru OS](https://github.com/maruos/maruos)) which has a very tight /system image. On devices with low memory or storage, the update-binary skips installation of SetupWizard, which overrides AOSP's Provision app. Unfortunately, the script currently [removes](https://github.com/MindTheGapps/vendor_gapps/blob/master/build/meta/com/google/android/update-binary#L98) the Provision app even when SetupWizard is not installed, which causes the device to remain in an uninitialized state (Home button doesn't work for example).

Running an open-source project myself, I know that PRs are much preferred over bug reports so I have submitted https://github.com/MindTheGapps/vendor_gapps/pull/11 to fix this.

Thanks for your work on supporting this very useful project!

**Comment by javelinanddart** [comment]
Resolved on P.
