### ISSUE TITLE
Question Regarding MindTheGApps Android 9.0/Lineage-16.0 for ARM/ARM32 devices...

### ISSUE THREAD

**Issue by Ibuprophen** [MindTheGapps/vendor_gapps-old#13]
Hello there @javelinanddart! :-)

I was wondering if you could please provide MindTheGApps Android 9.0/Lineage-16.0 for ARM/ARM32 devices because the link you specified where your releases are located (http://downloads.codefi.re/jdcteam/javelinanddart/gapps) are ARM64 only.

I was also unable to locate any releases of MindTheGApps Android 9.0/Lineage-16.0 for ARM/ARM32 devices devices after looking on multiple locations via the various directories within the "http://downloads.codefi.re/jdcteam/" and even tried to look within your "https://androidfilehost.com/?w=profile&uid=23501681358562483" Developer Directories as well.

It would be great If you could even provide me with the location of where any other individual(s) who has been actively releasing them (to prevent redundant releases).

Thank you very much for your time, patience and understanding with this! :-P 

~Ibuprophen

**Comment by npjohnson** [comment]
I hate to be that guy, but I'm going to link you what you linked:

http://downloads.codefi.re/jdcteam/javelinanddart/gapps

There's an arm zip at that very link.

MTG doesn't support Pie yet, tho.

**Comment by Ibuprophen** [comment]
Thank you very much for providing a helping hand @npjohnson but, unfortunately, that is for Android 8.1/Lineage-15.1 and i was asking about a release for Android 9/Lineage-16.0...


~Ibuprophen

**Comment by npjohnson** [comment]
Yeah, noted that and edited my post.

MTG doesn't support 9.0 yet.

**Comment by Ibuprophen** [comment]
I heard about that... I have a release (which happens to be the only one found) that seems to be working okay on the LineaseOS 16.0 Unofficial releases by Haggartk.

Also, throughout the XDA Forum, there's members who has been stating that the MindTheGApps releases for 8.1 work with the 9.0.

This is something that i haven't tried myself since i would prefer (as anyone should) a release specific for the 9.0.


~Ibuprophen

**Comment by npjohnson** [comment]
@ibuprophen1 haggertk didn't release an updated MTG.

Don't use 8.1 MTG on a 9.0 ROM... you'd be asking for problems with provisioning/SetupWizard. Just use OpenGApps for now.

MTG won't be releasing 9.0 GApps any time soon.

**Comment by Ibuprophen** [comment]
I see... Thank you very much @npjohnson for your clarification, time and understanding with this question! 

After trying out the MindTheGApps on LineageOS 15.1, I had ended up not liking it too much and went back to my previous use of OpenGApps Pico. 

This was a personal preference as I wasn't referring to any functional problem itself with MindTheGApps but, it wasn't as stripped down as I've preferred myself. 

I just personally prefer having only the Play Store and whatever makes it work. 

Keep up with the great work you and the Lineage Team does!!! :-) 


~Ibuprophen

**Comment by curiousrom** [comment]
@npjohnson wrote:
> @ibuprophen1 haggertk didn't release an updated MTG...

He did not say he did. He posted above:
>...on the LineaseOS 16.0 Unofficial releases by Haggartk.

BTW @ibuprophen1 you made 2 typos: it's LineageOS & hagg**e**rtk. ;)

**Comment by AndroidDeveloperLB** [comment]
How did you flash gapps ? It claims about not enough space...
EDIT: never mind. Found this:
https://forum.xda-developers.com/google-nexus-5/orig-development/repartition-nexus-5-repartition-t3844395
