### ISSUE TITLE
Samsung Galaxy S7 and MindTheGapps-8.1.0-arm64-20180808_153856

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [MindTheGapps/vendor_gapps-old#15]
Hi,

I tested on my Samsung Galaxy S7 with LineageOS 15.1 (unofficial) MindTheGapps-8.1.0-arm64-20180808_153856.zip.
After installing MindTheGapps from within TWRP (clean install) I get the installation wizard after boot.
The wizard asked me for my WiFi and then for PW.
But I got no keyboard, I got the Voice Assistant!
And the Voice Assistant wasn't usable (no reaction)!
I rebooted the device and used the open guest account of my WiFi...
Then I got a black screen were only the status bar on top (with e.g. the time) is visible...
I rebooted the phone again and got this time the msg "Searching for updated" (in German)...
...but the device was hanging on this point.
After some min. I rebooted the device again and run again into the "Searching for updates"-msg and the device was hanging on this point again.
So I wiped data again and moved on without MindTheGapps...

Hope my feedback/bug report helps with development.

**Comment by javelinanddart** [comment]
Can't reproduce here, sorry. The only keyboard thing we touch is adding a lib for swipe to work on AOSP keyboard.
