### ISSUE TITLE
Question/Clarification Regarding MindTheGApps... 

### ISSUE THREAD

**Issue by Ibuprophen** [MindTheGapps/vendor_gapps-old#16]
@npjohnson & @javelinanddart, since MindTheGApps 8.1 & 9.0 is now being released for the ARM device as reflected on the following link... 

http://downloads.codefi.re/jdcteam/javelinanddart/gapps

... can you please confirm its stability compared to OpenGApps? 

Thanks a Bunch! :-) 

~ Ibuprophen

**Comment by javelinanddart** [comment]
No. I don't use opengapps and this isn't really an appropriate question to ask a developer, anyways.

**Comment by Ibuprophen** [comment]
@javelinanddart, I apologize if my question was stated in a bad light as I didn't appropriately ask it.

My intent was regarding MindTheGApps for the ARM being stable enough for use with the Unofficial LineageOS 16.0 builds provided by @Haggertk. 

Shame on me in asking for such a comparison. 

Thanks a bunch! :-) 


~Ibuprophen
