### ISSUE TITLE
Upgrade from LOS 15 with MTG 8 to LOS 16 with MTG 9

### ISSUE THREAD

**Issue by Forage** [MindTheGapps/vendor_gapps-old#17]
Hi,

What is the recommended upgrade path from LOS 15 to 16 when having MTG 8 installed?

Flash LOS 16 followed by flashing MTG 9 wasn't a goos idea apparently. All gapps keep crashing.

What should I have done and how could I recover from the current situation? Preferably without a wipe that is...

**Comment by npjohnson** [comment]
You did something wrong then. Something persisted that shouldn't have.

you can likely just wipe /system and start over without wiping data.

**Comment by Forage** [comment]
Easy to say, not helping without trying to figure out what I supposedly did wrong.

For that particular situation did a wipe to solve the issue, but now after flashing a LOS build update I ran into the same issue again.

Exact steps performed:
1. Rebooted into recovery (slot B active)
2. Flashed the new LOS build
3. Flashed  TWRP
4. Flashed Magisk

No reboots in between.

After the reboot I keep getting spammed with "Google Play services keeps stopping" messages.

So I rebooted into recovery again, changed back to the previous slot B to flash the messed up slot again. This time I did:

1. Rebooted into recovery (slot B active)
2. Flashed the new LOS build
3. Flashed MTG 9
4. Flashed  TWRP
5. Flashed Magisk

The results are the same, with repeated messages.

What did I do wrong here, if anything? How can I update without issues?

**Comment by Forage** [comment]
I found the cause.
Unlike flashing a LOS build which will select the non-active slot to install to, MTG does not do so but installs to the currently active slot instead.

So a reboot to recovery is required between flashing LOS and MTG.

**Comment by npjohnson** [comment]
@Forage all of the details you just found out are detailed on your device's lineageos wiki page.

It describes exactly how to install on A/B, which requires the reboot to recovery between the installs.

**Comment by Forage** [comment]
There isn't a wiki page for my device (OnePlus 6 yet), nor for any A/B device for all I know and could find. And no mention of a reboot between a rom flash on the general gapps page neither, nor any mention of A/B on there.

**Comment by npjohnson** [comment]
Ah, so an unofficial device. Your XDA thread should be detailing this. If it isn't that's not something we can control.

As for instructions - I have a PS up to fix the GApps page, but here are numerous other A/B devices instructions to pull from.

https://wiki.lineageos.org/devices/nash
https://wiki.lineageos.org/devices/marlin
https://wiki.lineageos.org/devices/sailfish

We detailed the install process for A/B on our blog post for launching A/B as well, and on the upgrade post detailing 16.0.
