### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by Forage** [MindTheGapps/vendor_gapps-old#20]
Now with LineageOS 17.1 available, will there be a MindTheGapps 10?

**Comment by Forage** [comment]
Created ticket at gitlab instead

**Comment by curiousrom** [comment]
> Created ticket at gitlab instead

Link?

**Comment by Forage** [comment]
> > Created ticket at gitlab instead
> 
> Link?

https://lmgtfy.com/?q=Mindthegapps+gitlab
