### ISSUE TITLE
Why adding the Google application?

### ISSUE THREAD

**Issue by notorand-it** [MindTheGapps/vendor_gapps-old#4]
In the Pico version for 8.1 it's been bundled the "google" application which has never been present in the other gapps packages.
If that's mandatory in order to have gapps pico working, then forget about this issue.
But if it's not, why adding something that's not strictly needed?

**Comment by javelinanddart** [comment]
You need it on the system partition for "OK Google" anywhere to work

**Comment by notorand-it** [comment]
... and "ok Google" is mandatory also for Pico?

**Comment by javelinanddart** [comment]
There is no "pico". There's one package.
